[prune]
  go-tests = true
  unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/nozo-moto/go-nkf"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.0"
